name: ui_challenge_ticket
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/efe-kurnaz.jpg
    - assets/rodion-kutsaev.jpeg
    - assets/steve-johnson.jpeg
  fonts:
    - family: SF Pro Display
      fonts:
      - asset: fonts/SF-Pro-Display-Ultralight.otf
        weight: 100
      - asset: fonts/SF-Pro-Display-Thin.otf
        weight: 200
      - asset: fonts/SF-Pro-Display-Light.otf
        weight: 300
      - asset: fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: fonts/SF-Pro-Display-Heavy.otf
        weight: 800
      - asset: fonts/SF-Pro-Display-Black.otf
        weight: 900